# Dep2
version: v2beta1

localRegistry:
  enabled: false

vars:
  IMAGE: ${REGISTRY}/dep2

images:
  dep1:
    image: "${IMAGE}"

pipelines:
  build:
    run: |
      echo "Build dep2"
      build_images dep2

